# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('home', '0002_delete_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='functional_results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_results', models.CharField(max_length=128)),
                ('log_file', models.CharField(max_length=128)),
                ('start_time', models.CharField(max_length=128)),
                ('end_time', models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name='functional_test_run',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('product', models.CharField(max_length=32)),
                ('os', models.CharField(max_length=8)),
                ('test_type', models.IntegerField()),
                ('build_info', models.CharField(max_length=16)),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('total_ran', models.IntegerField()),
                ('total_pass', models.IntegerField()),
                ('total_fail', models.IntegerField()),
                ('status', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='functional_testcase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_name', models.CharField(max_length=128)),
                ('test_type', models.IntegerField()),
                ('test_comment', models.CharField(max_length=128)),
            ],
        ),
        migrations.AddField(
            model_name='functional_results',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.functional_test_run'),
        ),
        migrations.AddField(
            model_name='functional_results',
            name='test_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.functional_testcase'),
        ),
    ]
