# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 21:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_auto_20170224_2100'),
    ]

    operations = [
        migrations.RenameField(
            model_name='functional_results',
            old_name='job_id',
            new_name='job',
        ),
        migrations.RenameField(
            model_name='functional_results',
            old_name='test_id',
            new_name='test',
        ),
    ]
