# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-02-24 21:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_auto_20170224_2103'),
    ]

    operations = [
        migrations.RenameField(
            model_name='functional_results',
            old_name='test_results',
            new_name='test_result',
        ),
    ]
