# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 18:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_performance_results_performance_test_run_performance_testcase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='performance_results',
            name='job',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.performance_test_run'),
        ),
        migrations.AlterField(
            model_name='performance_results',
            name='test',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.performance_testcase'),
        ),
    ]
