# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-11 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_auto_20170405_1808'),
    ]

    operations = [
        migrations.AlterField(
            model_name='functional_test_run',
            name='end_time',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='functional_test_run',
            name='start_time',
            field=models.CharField(max_length=200),
        ),
    ]
