# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-16 18:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20170411_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='functional_results',
            name='area',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.AlterField(
            model_name='functional_results',
            name='log_file',
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name='functional_test_run',
            name='test_type',
            field=models.CharField(max_length=32),
        ),
        migrations.AlterField(
            model_name='functional_testcase',
            name='test_type',
            field=models.CharField(max_length=32),
        ),
    ]
